//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_VaApp {
	
	
	public partial class NewAmbassador {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divNotification;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl isError;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl isSuccess;
		
		protected System.Web.UI.WebControls.TextBox txtIRID;
		
		protected System.Web.UI.WebControls.DropDownList cbxTitle;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtCompanyTitle;

		protected System.Web.UI.WebControls.TextBox txtDescription;
		protected System.Web.UI.WebControls.DropDownList cbxCorpStaff;
		protected System.Web.UI.WebControls.TextBox txtEmail;
		protected System.Web.UI.WebControls.TextBox txtContactNumber;
		protected System.Web.UI.WebControls.FileUpload fuAmbassadorPhoto;
		protected System.Web.UI.WebControls.FileUpload fuTeamLogo;
		protected System.Web.UI.WebControls.TextBox txtTeam;
		protected System.Web.UI.WebControls.TextBox txtPassword;
		protected System.Web.UI.WebControls.TextBox txtCPassword;
		/// <summary>
		/// txtTeam control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtTeamLogo;
		protected System.Web.UI.WebControls.DropDownList ddTeams;
		/// <summary>
		/// txtTeam control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtBaseCountry;
		/// <summary>
		/// txtTeam control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtYearJoined;
		protected global::System.Web.UI.WebControls.TextBox txtRank;
	}
}
