//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_VaApp {
	
	
	public partial class NewCorpStaff {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divNotification;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl isError;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl isSuccess;
		
		protected System.Web.UI.WebControls.TextBox txtSearchID;
		
		protected System.Web.UI.WebControls.DropDownList cbxType;
		
		protected System.Web.UI.WebControls.DropDownList cbxTitle;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.TextBox txtCompanyTitle;
		
		protected System.Web.UI.WebControls.TextBox txtDepartment;
		
		protected System.Web.UI.WebControls.TextBox txtRegion;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtCPassword;
		
		protected System.Web.UI.WebControls.TextBox txtContactNumber;
		
		protected System.Web.UI.WebControls.FileUpload fuCorpPhoto;
		
		protected System.Web.UI.WebControls.TextBox txtCorpRank;
		
		protected System.Web.UI.WebControls.LinkButton lnkBtnCreate;
	}
}
